- name: Read DB secret from AWS Secrets Manager
  ansible.builtin.set_fact:
    db_secret: >-
      {{
        lookup(
          'amazon.aws.secretsmanager_secret',
          db_secret_name,
          region=aws_region
        ) | from_json
      }}
  delegate_to: localhost
  run_once: true
  no_log: true
